"""business: clientes, cotacoes, propostas, jobs, veiculos, imoveis

Revision ID: db3e30d3388b
Revises: 001
Create Date: 2026-08-20 09:40:28.618605

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "db3e30d3388b"
down_revision: str | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clientes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("cpf_idx", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("data_nascimento", sa.Date(), nullable=True),
        sa.Column("sexo", sa.String(length=1), nullable=True),
        sa.Column("estado_civil", sa.String(length=50), nullable=True),
        sa.Column("profissao", sa.String(length=50), nullable=True),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clientes_cpf_idx"), "clientes", ["cpf_idx"], unique=False)
    op.create_table(
        "cotacoes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cliente_id", sa.Uuid(), nullable=True),
        sa.Column("ramo", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "dados_risco", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("cotacao_id_cia", sa.String(length=100), nullable=True),
        sa.Column("premio_total", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "restricoes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("mensagens", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("necessita_vistoria", sa.Boolean(), nullable=False),
        sa.Column(
            "payload_original",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("versao_anterior_id", sa.Uuid(), nullable=True),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clientes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["versao_anterior_id"],
            ["cotacoes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "imoveis",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cliente_id", sa.Uuid(), nullable=False),
        sa.Column("cep", sa.String(length=8), nullable=False),
        sa.Column("logradouro", sa.String(length=255), nullable=True),
        sa.Column("numero", sa.String(length=20), nullable=True),
        sa.Column("tipo_imovel", sa.String(length=50), nullable=False),
        sa.Column("tipo_construcao", sa.String(length=50), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clientes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "veiculos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cliente_id", sa.Uuid(), nullable=False),
        sa.Column("fipe_codigo", sa.String(length=20), nullable=True),
        sa.Column("marca", sa.String(length=100), nullable=False),
        sa.Column("modelo", sa.String(length=100), nullable=False),
        sa.Column("ano_fabricacao", sa.Integer(), nullable=False),
        sa.Column("ano_modelo", sa.Integer(), nullable=False),
        sa.Column("placa", sa.String(length=10), nullable=True),
        sa.Column("chassi", sa.String(length=17), nullable=True),
        sa.Column("combustivel", sa.String(length=20), nullable=False),
        sa.Column("finalidade", sa.String(length=50), nullable=False),
        sa.Column("cep_pernoite", sa.String(length=8), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clientes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cotacao_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cotacao_id", sa.Uuid(), nullable=False),
        sa.Column("cia", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("tentativas", sa.Integer(), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cotacao_id"],
            ["cotacoes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "propostas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cotacao_id", sa.Uuid(), nullable=False),
        sa.Column("protocolo", sa.String(length=100), nullable=False),
        sa.Column("commissao_pct", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("plano_pagamento", sa.String(length=20), nullable=False),
        sa.Column("n_parcelas", sa.Integer(), nullable=False),
        sa.Column("valor_parcela", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "comissao_parcela", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("inicio_vigencia", sa.Date(), nullable=True),
        sa.Column("transmitida_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cotacao_id"],
            ["cotacoes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("propostas")
    op.drop_table("cotacao_jobs")
    op.drop_table("veiculos")
    op.drop_table("imoveis")
    op.drop_table("cotacoes")
    op.drop_index(op.f("ix_clientes_cpf_idx"), table_name="clientes")
    op.drop_table("clientes")
    # ### end Alembic commands ###
